
--CREACION TABLA TEMPORAL

CREATE TABLE temporal (
NOMBRE_CLIENTE	        VARCHAR2(255),
CORREO_CLIENTE	        VARCHAR2(255),
CLIENTE_ACTIVO	        VARCHAR2(255),
FECHA_CREACION	        VARCHAR2(255),
TIENDA_PREFERIDA	    VARCHAR2(255),
DIRECCION_CLIENTE	    VARCHAR2(255),
CODIGO_POSTAL_CLIENTE	VARCHAR2(255),
CIUDAD_CLIENTE	        VARCHAR2(255),
PAIS_CLIENTE	        VARCHAR2(255),
FECHA_RENTA	            VARCHAR2(255),
FECHA_RETORNO	        VARCHAR2(255),
MONTO_A_PAGAR	        VARCHAR2(255),
FECHA_PAGO	            VARCHAR2(255),
NOMBRE_EMPLEADO	        VARCHAR2(255),
CORREO_EMPLEADO	        VARCHAR2(255),
EMPLEADO_ACTIVO	        VARCHAR2(255),
TIENDA_EMPLEADO	        VARCHAR2(255),
USUARIO_EMPLEADO	    VARCHAR2(255),
CONTRASENA_EMPLEADO	    VARCHAR2(255),
DIRECCION_EMPLEADO	    VARCHAR2(255),
CODIGO_POSTAL_EMPLEADO	VARCHAR2(255),
CIUDAD_EMPLEADO	        VARCHAR2(255),
PAIS_EMPLEADO	        VARCHAR2(255),
NOMBRE_TIENDA	        VARCHAR2(255),
ENCARGADO_TIENDA	    VARCHAR2(255),
DIRECCION_TIENDA	    VARCHAR2(255),
CODIGO_POSTAL_TIENDA    VARCHAR2(255),
CIUDAD_TIENDA	        VARCHAR2(255),
PAIS_TIENDA	            VARCHAR2(255),
TIENDA_PELICULA	        VARCHAR2(255),
NOMBRE_PELICULA	        VARCHAR2(255),
DESCRIPCION_PELICULA	VARCHAR2(255),
ANO_LANZAMIENTO	        VARCHAR2(255),
DIAS_RENTA	            VARCHAR2(255),
COSTO_RENTA	            VARCHAR2(255),
DURACION	            VARCHAR2(255),
COSTO_POR_DANO	        VARCHAR2(255),
CLASIFICACION	        VARCHAR2(255),
LENGUAJE_PELICULA	    VARCHAR2(255),
CATEGORIA_PELICULA	    VARCHAR2(255),
ACTOR_PELICULA          VARCHAR2(255)

);




--ELIMINAR TABLA TEMPORAL

drop table temporal;







